import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar, { NavLinkItem } from "@/components/shadcn-space/blocks/hero-02/navbar";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData: NavLinkItem[] = [
    { name: 'Home', href: '/' },
    { name: 'Todo', href: '/todo' },
    { name: 'Contact', href: 'https://github.com/mdafaadiwinata' },
    { name: 'Docs', href: 'https://www.prisma.io/docs/guides/frameworks/nextjs#23-add-dotenv-to-prismaconfigts' },
  ]
  return (
    <html
      lang="en"
      className={`${jakartaSans.variable} h-full antialiased`}
    >
      <body className="flex flex-col"><Navbar navData={navData} />{children}</body>
    </html>
  );
}
